package com.pki.security.PKISecurity.enums;

public enum ExtensionType {
    BASIC_CONSTRAINTS,
    KEY_USAGE,
    SUBJECT_KEY_IDENTIFIER,
    SUBJECT_ALTERNATIVE_NAME,
    ISSUER_ALTERNATIVE_NAME,
    EXTENDED_KEY_USAGE,
    AUTHORITY_KEY_IDENTIFIER,
    CRL_DISTRIBUTION_POINTS,
    AUTHORITY_INFORMATION_ACCESS,
    CERTIFICATE_POLICIES,
    INHIBIT_ANY_POLICY,
    POLICY_CONSTRAINTS,
    POLICY_MAPPINGS,
    NAME_CONSTRAINTS,
    OCSP_NO_CHECK,
    CRL_NUMBER,
    DELTA_CRL_INDICATOR,
    FRESHEST_CRL,
    REASON_CODE
}
